version: '3.8'

services:
  # 1. Datenbank (MySQL)
  db:
    image: mysql:8.0
    container_name: agora-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: agora_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  # 2. API (Node/Express)
  backend:
    build: ./backend
    container_name: agora-backend
    restart: always
    depends_on:
      - db
    networks:
      - app-network

  # 3. Reverse Proxy & Static Webserver (NGINX)
  nginx:
    image: nginx:alpine
    container_name: agora-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./Frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge