server {
    listen 80;
#    listen 443;
    
    # Das Verzeichnis, in das wir im Dockerfile kopiert haben
    root /usr/share/nginx/html;
    index index.html;

    proxy_buffer_size 128k;
    proxy_buffers 4 256k;
    proxy_busy_buffers_size 256k;

    sendfile off; # Deaktiviert die fehleranfällige Kernel-Optimierung in Docker
    tcp_nopush on;
    tcp_nodelay on;

    location / {
        # Wichtig für Vue-Router: Wenn eine Datei nicht gefunden wird, 
        # sende die Anfrage an index.html
        try_files $uri $uri/ /index.html;
    }

    # API-Weiterleitung zum Backend
    location /api/ {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /auth/ {
        proxy_pass http://keycloak:8080/auth/;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port 80;

    }
}


