server {
    listen 80;

    # Ziel 1: Frontend (Statische Assets aus dem Dateisystem)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Ziel 2: Reverse Proxy zum Backend (API REQUEST -> JSON)
    location /api/ {
        proxy_pass http://backend:3000/; # Leitet an den Service 'backend' weiter
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /auth/ {
        proxy_pass http://keycloak:8080/;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port 80;
    }
}
}
